name: Check Run Workflow
on:
  check_run:
    types:
      - requested_action

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Tests
        run: |
          echo OK
